"""Generate on-device assets for the ESP32 sketches:
  - firmware/board_a_embeddings/vocab.h : token id -> raw UTF-8 bytes
  - Prints the prompt token ids for the demo prompt.

Adapted from slvDev/esp32-ai/src/gen_assets.py.
"""

import os
import sys

from tokenizers import Tokenizer

HERE = os.path.dirname(os.path.abspath(__file__))
TOK = os.path.join(HERE, "..", "data", "tokenizer", "bpe32768.json")
OUT_DIR = os.path.join(HERE, "..", "firmware", "board_a_embeddings")
PROMPT = "Once upon a time"


def main():
    tok_path = sys.argv[1] if len(sys.argv) > 1 else TOK
    tok = Tokenizer.from_file(tok_path)
    V = tok.get_vocab_size()

    blob = bytearray()
    offs = [0]
    for i in range(V):
        s = tok.decode([i])
        blob.extend(s.encode("utf-8"))
        offs.append(len(blob))

    os.makedirs(OUT_DIR, exist_ok=True)
    out = os.path.join(OUT_DIR, "vocab.h")
    with open(out, "w") as f:
        f.write("// Generated by src/gen_assets.py -- token id -> raw UTF-8 bytes.\n")
        f.write("#ifndef VOCAB_H\n#define VOCAB_H\n")
        f.write(f"#define VOCAB_N {V}\n")
        f.write(f"static const unsigned char VOCAB_BLOB[{len(blob)}] = {{\n")
        for i in range(0, len(blob), 20):
            f.write("  " + ",".join(str(b) for b in blob[i:i+20]) + ",\n")
        f.write("};\n")
        f.write(f"static const int VOCAB_OFF[{len(offs)}] = {{\n")
        for i in range(0, len(offs), 20):
            f.write("  " + ",".join(str(o) for o in offs[i:i+20]) + ",\n")
        f.write("};\n#endif\n")

    print(f"wrote {out}: {V} tokens, blob {len(blob)/1024:.0f} KB")

    ids = tok.encode(PROMPT).ids
    print(f'prompt "{PROMPT}" -> {len(ids)} ids: {ids}')
    print(f"round-trip: {tok.decode(ids)!r}")
    print("\nPaste into the sketch:")
    print(f"static const int PROMPT_IDS[] = {{{', '.join(map(str, ids))}}};")

    # Also copy vocab.h to board_c for decoding
    out_c = os.path.join(HERE, "..", "firmware", "board_c_decoder", "vocab.h")
    os.makedirs(os.path.dirname(out_c), exist_ok=True)
    import shutil
    shutil.copy2(out, out_c)
    print(f"Also copied to {out_c}")


if __name__ == "__main__":
    main()
